### ISSUE TITLE
targetRowHeight property not respected for reduced number of photos.

### ISSUE THREAD

**Issue by ashleydavis** [neptunian/react-photo-gallery#136]
First of all, thanks so much for this library. It's really good and I'm hoping to use it in a commercial product.

I came across a weird issue and you might be able to help me understand how to work around it.

I want to use the property targetRowHeight to constrain the height of photos to a specified amount. This works well when there's a lot of photos, but when you cut back the number of photos it no longer respects the value that I assign to targetRowHeight.

I'll show you want I mean.

I start with this example: https://codesandbox.io/s/9yx911wl9y

Then I set targetRowHeight as follows:

![image](https://user-images.githubusercontent.com/625126/58223574-94007800-7d5d-11e9-8cb1-d0fb67020377.png)

When there's many photos this gives me the affect that I want:

![image](https://user-images.githubusercontent.com/625126/58223587-aaa6cf00-7d5d-11e9-9e36-f3223e6dc601.png)

Now I reduce the number of photos (to simulate a user with few photos in their gallery):

![image](https://user-images.githubusercontent.com/625126/58223609-c4e0ad00-7d5d-11e9-9342-8218d4193b98.png)

Now the row height for the photos is very large:

![image](https://user-images.githubusercontent.com/625126/58223622-ce6a1500-7d5d-11e9-97c8-a2db54028c3a.png)

Does it work this way by design?

Is there anyway that I can control this behaviour?

Thanks so much.

**Comment by neptunian** [comment]
Hi,
The problem is that given the width of your container, the row has to grow in height in order to keep the aspect ratio but fill the entire width to create a justified gallery.  So these results make sense.  If you were to try to constrain the height then you could not preserve the aspect ratios of both images in the same row. A Google Photos photo album behaves similarly:

Many photos:
<img width="1613" alt="Screen Shot 2019-05-23 at 3 29 07 PM" src="https://user-images.githubusercontent.com/1676003/58280882-9ff53580-7d6f-11e9-82f9-fa070c6ed58e.png">

One Photo:
<img width="1604" alt="Screen Shot 2019-05-23 at 3 28 34 PM" src="https://user-images.githubusercontent.com/1676003/58280890-a84d7080-7d6f-11e9-9f10-bfd1b5e54b0f.png">

 Unfortunately, there isn't a workaround other than to make the width of the gallery smaller.  It's possible I can add in as a flag for the user to set to handle a special case like this where essentially they don't feel like they have a complete gallery and and want the row to be shorter as if they had many images on it and have white space to the side to show an incomplete row.  One hack you can do in the meantime is pass in a transparent image several times until you force it into being the row height you desire.  So you can count your images and if you know your images are going to be very few you can push in some "ghost images".  Be aware of dealing with the responsive aspect of mobile widths as you would not want them in that case.

**Comment by ashleydavis** [comment]
Thanks for you quick response.

I understand that the current behaviour is probably what most people want from a gallery. It's just not what I want ;)

I would hope that if I set `targetRowHeight` then the gallery respects that's what I want the row height to be, but I get that you don't want to change the behaviour of this property.

Would you consider introducing a new property called `rowHeight` that specifies the absolute row height?

**Comment by neptunian** [comment]
I'm not sure you understand.  You can't have a fully justified gallery and set the row height at the same time whilst keeping the aspect ratios of all images in the row.  Its not mathematically possible.  If you want to set a fixed row height you need to use square images for all your photos.  If you want a full explanation this blog might help your understanding: https://medium.com/google-design/google-photos-45b714dfbed1  Scroll to Justified Gallery section.

**Comment by ashleydavis** [comment]
I think you are misunderstanding what I want.

I want the size of the photos not to change even when photos are removed from the gallery.

Consider the following screenshot. Most of the photos are removed except for two. I want those two to remain the same width and height:

![image](https://user-images.githubusercontent.com/625126/58296000-2879e180-7e15-11e9-8192-3d6c1bbd569c.png)

**Comment by ryanwalters** [comment]
We're locked in to v6.x due to this issue here @britannica. The desired behavior would be to have the last row not attempt to resize the images to fill the entire row (e.g. 1 enormous image = bad).

**Comment by huumn** [comment]
In case anyone is looking for a solution I wrap the gallery to achieve this for https://grepmed.com. If the cumulative width of the thumbnails and margins is greater than the width of the wrapping container, I use the gallery otherwise I just put them in a div as a row with the appropriate height.

```js
function RowGallery ({ targetRowHeight, margin, onClick, renderImage, photos }) {
  const handleClick = (event, { index }) => {
    onClick(event, {
      index,
      photo: photos[index],
      previous: photos[index - 1] || null,
      next: photos[index + 1] || null
    })
  }

  return (
    <div className={styles.rowGallery}>
      {photos.map((photo, index) => {
        // compute the "natural height and width" of the photo
        photo.width = photo.width * (targetRowHeight / photo.height)
        photo.height = targetRowHeight
        return renderImage({
          key: photo.key || photo.src,
          index,
          margin,
          onClick: onClick ? handleClick : null,
          photo
        })
      })}
    </div>
  )
}

function GalleryWrapper (props) {
  const { targetRowHeight, margin, photos } = props
  const [containerWidth, setContainerWidth] = useState(0)
  const galleryRef = useRef(null)

  useLayoutEffect(() => {
    let animationFrameID = null
    const observer = new ResizeObserver(entries => {
      // only do something if width changes
      const newWidth = entries[0].contentRect.width
      if (containerWidth !== newWidth) {
        // put in an animation frame to stop "benign errors" from
        // ResizObserver https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded
        animationFrameID = window.requestAnimationFrame(() => {
          setContainerWidth(Math.floor(newWidth))
        })
      }
    })
    observer.observe(galleryRef.current)
    return () => {
      observer.disconnect()
      window.cancelAnimationFrame(animationFrameID)
    }
  })

  if (!containerWidth) return <div ref={galleryRef}>&nbsp;</div>

  // compute the cumulative width of our photos, breaking if the row will wrap
  let sumWidth = 0
  for (const photo of photos) {
    sumWidth += photo.width * (targetRowHeight / photo.height) + 2 * margin
    if (sumWidth > containerWidth) {
      break
    }
  }

  return (
    <div ref={galleryRef}>
      {sumWidth > containerWidth
        ? <Gallery {...props} /> : RowGallery(props)}
    </div>
  )
}
```
