### ISSUE TITLE
Gallery inside a fixed size div forces scroll when adding a single thumbnail image

### ISSUE THREAD

**Issue by thushar10** [neptunian/react-photo-gallery#142]
Gallery component inside a fixed size div forces scroll when adding a single thumbnail image.  Expected result would be for the image to fit exactly in the div. On adding more images for a certain width the images are stacked up one below other. This is not the case when there is no container div and viewed on mobile screen. Only in case where there is a container div below a certain length. 
![single](https://user-images.githubusercontent.com/9011976/61236661-2ddd1380-a756-11e9-9d5a-ad09b2586ed9.png)
![multiple](https://user-images.githubusercontent.com/9011976/61236662-2ddd1380-a756-11e9-8aaa-1692306b4676.png)

**Comment by neptunian** [comment]
Forces scroll in which direction?  You can't set a height so that will scroll if you do but it shouldn't scroll width wise.  

As far as images stacked, once the container gets to a certain width, it will use default settings and not have many images in a row.  Overriding the `limitNodeSearch` prop will change that.  I suggest you read the docs and try to understand how that property works because using if incorrectly can provide bad results.
