### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by wamatt** [neptunian/react-photo-gallery#19]
Looked briefly at the codebases of your project and this one:

https://github.com/benhowell/react-grid-gallery

It would seem perhaps your code and efforts have been unattributed / unacknowledged by this newer fork?

**Comment by neptunian** [comment]
@wamatt  Thanks for bringing it to my attention.

**Comment by wamatt** [comment]
Of course. I'm sure it was an innocent oversight if it indeed was copied without attribution!

**Comment by benhowell** [comment]
I can assure you that the code is my own. The libraries do a similar thing in some respects but I can assure you that it is my own work. I have also seen this same rumour spread on HN and reddit and am unsure as to why. 

I based the first release (v0.0.2) on the basic gallery used by @jossmac for his demo of react-images (demo has since changed) but aside from standard react hooks and a few function names, the code has always done a substantially different job, and as such, is quite different. 

Regards,
Ben.
