### ISSUE TITLE
Add gap property to Gallery

### ISSUE THREAD

**Issue by jaycincotta** [neptunian/react-photo-gallery#215]
Could a `gap` property be added to Gallery?

Currently, Gallery accepts a `margin` property to add space around each elements in the gallery.  Since margin is also applied to the external edges of the gallery, the gallery as a whole is offset from it's container.  This is a general problem with grids and [gap is perfect for internal margins](https://bryanlrobinson.com/blog/gap-provides-bright-future-for-margins-in-flex-as-well-as-grid/).

An alternative to adding a new property would be to refine the semantics of the existing `margin` property to only apply to internal margins.

**Comment by igordanchenko** [comment]
You can work this around by applying negative margin to the gallery container. 

You are also more than welcome to take a look at [react-photo-album](https://react-photo-album.com) ([npm](https://www.npmjs.com/package/react-photo-album), [GitHub](https://github.com/igordanchenko/react-photo-album)) since react-photo-gallery is no longer maintained.

**Comment by jaycincotta** [comment]
the link to react-photo-album is broken.

**Comment by igordanchenko** [comment]
Updated the links above.

**Comment by jaycincotta** [comment]
Found it! https://github.com/igordanchenko/react-photo-album

It looks like a brand new repo just started this week.  Is that right, Igor?

**Comment by igordanchenko** [comment]
That doesn't sound right. The first release was published in December 2021.

**Comment by jaycincotta** [comment]
My bad.  react-photo-album looks promising.  I've opened a feature request on repo related to upgrading from react-photo-gallery
