### ISSUE TITLE
Video Support?

### ISSUE THREAD

**Issue by fisnik** [neptunian/react-photo-gallery#23]
So far the best thought out media gallery for react that I could find. Any plans on supporting videos?

**Comment by neptunian** [comment]
@fisnik  i've never thought about that, but I'll give it some thought.  I do like how Flickr is able to support that option.

**Comment by neptunian** [comment]
@fisnik the latest version of this component doesnt depend on Lightbox and the user can do whatever they want when someone clicks on a Gallery photo.  If you choose to continue using react-images, you can submit a video support suggestion there. https://github.com/jossmac/react-images
As for this gallery, perhaps there can be a media type prop for each image so that if its a video type we can display a little video icon over the image to indicate it is a movie?  One would still need to pass in an image.
