### ISSUE TITLE
Add ability to make cols vary

### ISSUE THREAD

**Issue by neptunian** [neptunian/react-photo-gallery#43]
Some rows having 2 images, others such as a panorama spanning the entire row (1 col); user defined.

**Comment by iMerica** [comment]
Currently, if there are 7 images in the photo set and `cols` is set to 3, the component will display 3 images per row for the first two rows and one orphaned image on the last row using only 1/3rd of available space. See below.

![grid-issues](https://cloud.githubusercontent.com/assets/487897/23929820/c33f8956-08e5-11e7-9d23-273608e71ec0.png)


It would be good to make `cols` only applicable to rows that have enough images to support it. Otherwise, use the entire space.

**Comment by neptunian** [comment]
@iMerica  this is correct behavior.  it solves the other issue you had brought up about the last image being stretched and distorted.  it's very jarring to have the last image have a very tall row height because its perhaps a portrait sized image trying to stretch the width of the app.

**Comment by iMerica** [comment]
Ahh that make sense now - thanks for explaining the motivation behind that. In my application, its users who are the ones uploading images of varying quantities and aspect ratios and all the images combined need to fit into a perfect quadrilateral/rectangle (I forked this repo to achieve that.)

One idea to satisfy all of the above use cases would be to sort all image aspect ratios so that a portrait image is never the last image in a hanging row 💡 .

**Comment by neptunian** [comment]
@iMerica  hopefully not all of your images are portrait!  perhaps we can add an api option where there are no trailing images so the last image goes into the last row.
