### ISSUE TITLE
Use differnt attribute instead of src

### ISSUE THREAD

**Issue by shogan94** [neptunian/react-photo-gallery#87]
Is it possible to pass a function to get the right value or a property name to `Gallery` so we don't have to use `src`? 

I'm following you're LightBox example but want to use thumbnails for the gallery and the full res for the LightBox but don't want to have separate arrays. 

Just wondering if that's possible with the current code? If not would you be open implementing it or allowing me to look at it? 

Right now each object in my array looks like this....
```
{
   src: 'urlToFullRes',
   thumbnail: 'urlToThumbnail',
   width: calculatedWidthRatio.
   height: calculatedHeightRation
}
```

**Comment by neptunian** [comment]
i think it should be called 'src' because that's the name of the attribute of the image tag.  the react-images component requires different data than this component so i'm not sure its a good idea to build around that.  for example 'srcSet' and 'sizes' are also used in both components but should have different values as well.
